name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push code to Windows Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true 

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 144.91.100.130 >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          scp -r -P 22 ./src/* Administrator@144.91.100.130:/C:/Aktix/
