name: Deploy to Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push code to Windows Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.PROD_DEPLOY_KEY }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 ${{ secrets.PROD_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          scp -r -P 22 ./src/* Administrator@${{ secrets.PROD_SERVER_IP }}:/C:/Aktix/
